---
title: "Union Membership in the United States"
---

```{r, message=FALSE}
library(tidyr)
library(dplyr)
library(stringr)
library(ggplot2)
knitr::opts_knit$set(root.dir = here::here())
theme_set(new = theme_minimal())
theme_update(plot.title = element_text(size = 10),
             axis.title = element_text(size = 9))
```

## Read Data

```{r}
demographics <- read.csv("2023_09_05_union_membership/data/demographics.csv")
wages <- read.csv("2023_09_05_union_membership/data/wages.csv")
states <- read.csv("2023_09_05_union_membership/data/states.csv")
```

## Explore Data

```{r}
glimpse(demographics)
```

```{r}
summary(demographics)
```

```{r}
head(table(demographics$facet))
```

```{r}
glimpse(wages)
```

```{r}
summary(wages)
```

```{r}
head(table(wages$facet))
```

## Union Membership over Time

```{r, fig.width=12, fig.height=10}
wages <- wages %>%
  mutate(
    facet_group = case_when(
      str_detect(facet, "all wage") ~ "all salary workers",
      str_detect(facet, "demographics") ~ "demographics",
      str_detect(facet, "private sector") ~ "private sector",
      str_detect(facet, "public sector") ~ "public sector",
    )) %>%
  mutate(
    facet_group = if_else(is.na(facet_group), facet, facet_group)
  )

wages %>%
  filter(!facet_group %in% "demographics") %>%
  mutate(facet_group = str_to_upper(facet_group)) %>%
  group_by(year, facet_group) %>%
  summarise("Union Wage" = mean(union_wage),
            "Non-Union Wage" = mean(nonunion_wage)) %>%
  pivot_longer(cols = c("Union Wage", "Non-Union Wage")) %>%
  ggplot(aes(x = year, y = value, group = name, color = name)) +
  geom_line(linewidth = 2, lineend = "round") +
  scale_color_manual(values = c("#EEAB65", "#7ED5B8")) +
  facet_wrap(~facet_group) +
  ylab("Hourly Earnings in Nominal $") +
  labs(title = "Hourly Earnings of Wage and Salary Workers in the U.S.",
       subtitle = "Evolution by Sector",
       caption = "\nData Sources: May Current Population Survey (CPS) and the CPS Outgoing Rotation Group (ORG) Earnings Files\n© 2023 by Barry T. Hirsch, David A. Macpherson, and William E. Even") +
  theme_minimal() +
  theme(legend.position = "top",
        legend.title = element_blank(),
        plot.background = element_rect(fill = "black"),
        panel.grid = element_line(color = "grey20"),
        axis.text = element_text(color = "grey80", size = 13),
        axis.title.y = element_text(color = "grey80", size = 16),
        axis.title.x = element_blank(),
        plot.title = element_text(color = "grey80", size = 26, face = "bold"),
        plot.subtitle = element_text(color = "grey80", size = 20),
        strip.text = element_text(color = "grey80", size = 12),
        legend.text = element_text(color = "grey80", size = 14),
        legend.justification = c(0,1),
        plot.caption = element_text(color = "grey80"))
```


